name: smartdumbbell
description: Application mobile pour SmartDumbbell - Coach personnel intelligent
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Interface
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Bluetooth
  flutter_blue_plus: ^1.31.0
  permission_handler: ^11.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Graphiques
  fl_chart: ^0.65.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.2
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
